export const offerURL = "https://academics.newtonschool.co/api/v1/bookingportals/offers";
export const projectID = "7xdkvg8p1bu0";
export const logInURL = "https://academics.newtonschool.co/api/v1/bookingportals/login" ;
export const singUpURL = "https://academics.newtonschool.co/api/v1/bookingportals/signup";
export const searchFLightURL = "https://academics.newtonschool.co/api/v1/bookingportals/flight?search=";
export const searchAirporttURL = "https://academics.newtonschool.co/api/v1/bookingportals/airport?search=";
export const serachHOtelURL = "https://academics.newtonschool.co/api/v1/bookingportals/hotel?search=";
export const gettingLocationURL = "https://academics.newtonschool.co/api/v1/bookingportals/city";
export const trainSearchURL = "https://academics.newtonschool.co/api/v1/bookingportals/train?search=";
export const searchBurURL = "https://academics.newtonschool.co/api/v1/bookingportals/bus?search=";
export const BookingConfirmationOrHistoryURL = "https://academics.newtonschool.co/api/v1/bookingportals/booking";